/* Main.ino file generated by New Project wizard
 *
 * Created:   qua nov 20 2019
 * Processor: Arduino Mega
 * Compiler:  Arduino AVR (Proteus)
 */

void setup()
 { // put your setup code here, to run once:
 }

void loop()
 { // put your main code here, to run repeatedly:
 }
